### ISSUE TITLE
Fix for deprecated key derivation warning

### ISSUE THREAD

**Issue by ghost** [simplepush/send-encrypted#1]
I've been getting the following warning when I execute send-encrypted.sh for a while now and I finally got around to looking into it:

`*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.`

I was able to fix this by changing some lines in the function `encrypt()` to:
`echo -n "${3}" | openssl aes-128-cbc -pbkdf2 -iter 1000 -base64 -K "${1}" -iv "${2}" | awk '{print}' ORS='' | tr '+' '-' | tr '/' '_'`
and 
`iv=$(openssl enc -aes-128-cbc -pbkdf2 -iter 1000 -k dummy -P -md sha1 | grep iv | cut -d "=" -f 2)`

(I changed the backticks to `$(...)` in this post so the markdown would display the code properly)

I have no idea if that is the best way to do it from a cryptography perspective, but it doesn't seem to break anything... so far.

**Comment by ghost** [comment]
I found this works only for openssl v1. 1.1, which is fine for newer versions of Ubuntu (works fine in 18.04), but `pbkdfs2` is  unavailable in openssl 1.1.0 which is the version on my one box running Ubuntu 14.04.  I'll have to add an openssl version check that sends a different cli args for openssl depending on the version. Maybe there's a more direct way to test for the existence of a particular key derivation function. (Or maybe I just need to upgrade!)

**Comment by wfinn** [comment]
Since I have the same problem I vote for this. Until then, maybe this helps.
```
54c54
< iv=`openssl enc -aes-128-cbc -k dummy -P -md sha1 | grep iv | cut -d "=" -f 2`
---
> iv=`openssl enc -aes-128-cbc -k dummy -P -md sha1 >/dev/stdout 2>/dev/null | grep iv | cut -d "=" -f 2`
```

**Comment by ghost** [comment]
Thanks. I have openssl upgraded to 1.1.1 on all my machines, so I can use pbkdfs2 now, obviating the need for a workaround.

You can also use the simplepush API via Python, which does not produce a key derivation warning. I've written a little Python3 wrapper if anyone is interested: [spush.py](https://gist.github.com/SyntrophicConsortium/2fc7447ddcd1aa951852079e376aa93e)

It requires the simplepush module, which can be downloaded via pip.

**Comment by simplepush** [comment]
Thank you. For now I'll just require openssl v1.1.1 or newer.
